### ISSUE TITLE
ERROR: could not insert module fl2000.ko: Operation not permitted

### ISSUE THREAD

**Issue by dan1lo** [klogg/fl2000_drm#7]
Hi, i can`t install. i got ERROR: could not insert module fl2000.ko: Operation not permitted. Anyone can help ?

**Comment by klogg** [comment]
It can be anything :) but for now - please note that this is work in progress (latest code revision can read EDIDs and start setting up the DRM/KMS FB).

**Comment by diegodlpereira** [comment]
@dan1lo you might need to disable secure boot in BIOS/UEFI
